<script setup lang="ts">
import {
  Captions,
  Languages,
  Combine,
  History,
  Settings2,
  HardDrive,
  CircleHelp,
  CloudUpload,
  FileText,
  ArrowRight,
  Check,
  ChevronDown,
  ChevronRight,
  ChevronLeft,
  X,
  Play,
  Pause,
  RotateCcw,
  Download,
  Trash2,
  Plus,
  Search,
  KeyRound,
  Eye,
  EyeOff,
  Info,
  BookOpen,
  ListChecks,
  LoaderCircle,
  CircleCheck,
  CircleAlert,
  Sparkles,
  ArrowUpRight,
  ShieldCheck,
  Clock3,
  Menu,
  LockKeyhole,
  SlidersHorizontal,
  FileJson,
  Sun,
  Moon,
} from '@lucide/vue'
const icons = {
  captions: Captions,
  languages: Languages,
  combine: Combine,
  history: History,
  settings: Settings2,
  storage: HardDrive,
  help: CircleHelp,
  upload: CloudUpload,
  file: FileText,
  arrow: ArrowRight,
  check: Check,
  down: ChevronDown,
  right: ChevronRight,
  left: ChevronLeft,
  close: X,
  play: Play,
  pause: Pause,
  retry: RotateCcw,
  download: Download,
  trash: Trash2,
  plus: Plus,
  search: Search,
  key: KeyRound,
  eye: Eye,
  eyeOff: EyeOff,
  info: Info,
  book: BookOpen,
  list: ListChecks,
  loading: LoaderCircle,
  success: CircleCheck,
  alert: CircleAlert,
  sparkle: Sparkles,
  external: ArrowUpRight,
  shield: ShieldCheck,
  clock: Clock3,
  menu: Menu,
  lock: LockKeyhole,
  sliders: SlidersHorizontal,
  json: FileJson,
  sun: Sun,
  moon: Moon,
}
defineProps<{ name: keyof typeof icons; size?: number }>()
</script>

<template><component :is="icons[name]" :size="size ?? 18" :stroke-width="1.7" aria-hidden="true" /></template>
